version: '2'
services:
  influxdb:
      image: influxdb:1.3.7
      volumes:
        - ./influxdb/data:/var/lib/influxdb
        - ./influxdb/config/:/etc/influxdb/
  realtimestatistics:
      build: .
      ports:
        - 7000:7000
      links:
        - influxdb:influxdb
      depends_on:
        - influxdb
